### ISSUE TITLE
Gesior Bug Players Online!

### ISSUE THREAD

**Issue by Hrubesch** [marcomoa/gesior-aac#1]
![weq](https://user-images.githubusercontent.com/19508861/52170352-a794be00-272f-11e9-892b-8ee1b1210818.png)

**Comment by ZeroSkywalker** [comment]
Change this code
`<?php
					if($config['status']['serverStatus_online'] == 1)
						$players_online1 = $config['status']['serverStatus_players'].' Players Online&nbsp;';
					else
						$players_online1 = ' Server Offline&nbsp;';
				?>`

For this
`<?php
if($config['status']['serverStatus_online'] = 1)
    {
      $players_online1 = $SQL->query("SELECT count(*) total FROM players_online")->fetchAll()[0]['total'];
      $players_online1 = $players_online1.' Players Online ';
    }
    else
    {
      $players_online1 = 'Server Offline ';
    }
?>`
