### ISSUE TITLE
Lostaccount.php | SQL Inject

### ISSUE THREAD

**Issue by marcomoa** [marcomoa/gesior-aac#2]
Some inputs from the **lostaccount.php** page leave some security holes open to the database, allowing the malicious user to make malicious commands.

A simple way to "work around" this problem is to block the right mouse button, of course, this is not the best way but it can help.

**Comment by ZeroSkywalker** [comment]
What do you have to do exactly? I could fix it

**Comment by ivenspontes** [comment]
It's simple, just implement an ORM.

**Comment by marcomoa** [comment]
@ZeroSkywalker From what I understood of the structures of the site, several tables were made allowing to inject sql, would have to give a better revision in all the pages.
apparently also exists in some "ajax" project files.

**Comment by ZeroSkywalker** [comment]
You can add an Anti Inject, which what it would do is not be able to execute any malicious commands. I have it installed and it is working.

**Comment by marcomoa** [comment]
@ZeroSkywalker I think the best way is to rewrite the tables correctly.

**Comment by marcomoa** [comment]
Fixed
