### ISSUE TITLE
Fundo azul

### ISSUE THREAD

**Issue by ZeroSkywalker** [marcomoa/Gesior-AAC#3]
Quando dou f5 para a página, isso acontece. Isso interfere com o fadein além de parecer ruim.

![captura de pantalla 693](https://user-images.githubusercontent.com/39470402/42676132-8d4132b6-863c-11e8-859d-624230671a38.jpg)

**Comment by Riicksouzaa** [comment]
Hello, that was fixed on the real project.:
https://github.com/Riicksouzaa/TheRealGesiorFerobra

**Comment by marcomoa** [comment]
Fixed

**Comment by Riicksouzaa** [comment]
kk
