### ISSUE TITLE
Duvida Pagseguro

### ISSUE THREAD

**Issue by jeckestripador** [marcomoa/Gesior-AAC#5]
Ola, não estou conseguindo prosseguir a partir desta tela, clicando no botão next, nada acontece!
![problem](https://user-images.githubusercontent.com/29901459/43295727-3c2b9b3c-911d-11e8-9b70-c180c6d4fc01.jpg)

**Comment by marcomoa** [comment]
Verifique se a configuração está correta, acabei de testar novamente e tudo funciona corretamente

**Comment by jeckestripador** [comment]
As configurações necessarias estao todas em config/config.php?
/**
 * PAGSEGURO FIXED
 */
$config['pagseguro']['testing'] = true;
$config['pagseguro']['lightbox'] = true;
$config['pagseguro']['tokentest'] = "**alterei aqui**";

# Pagseguro configs
$config['pagseguro']['email'] = "**alterei aqui**";
$config['pagseguro']['token'] = "**alterei aqui**";
$config['pagseguro']['produtoNome'] = 'Tibia Coins';
$config['pagseguro']['urlRedirect'] =  $config['base_url'];
$config['pagseguro']['urlNotification'] = $config['base_url'].'retpagseguro.php';
$config['pagseguro']['offers'] = [
    500=>75,
    800=>125,
    1500=>250,
    2800=>500,
    4900=>1000
];

Não alterei mais nada!

**Comment by mattos123** [comment]
comigo está 100%.

**Comment by Riicksouzaa** [comment]
Manda um print da tela do console para dar uma analisada, lembre-se que na configuração que você está usando é necessário configurar o TOKEN TEST de acordo com o [SANDBOX](https://sandbox.pagseguro.uol.com.br)

**Comment by Riicksouzaa** [comment]
Caso queira usar a forma em produção deve-se trocar a opção.
```php
$config['pagseguro']['testing'] = true;
```
Para 
```php
$config['pagseguro']['testing'] = FALSE;
```

**Comment by talistf** [comment]
Estou com o mesmo problema, creio que deva ser alguma configuração do Linux.
