### ISSUE TITLE
Sistema de Ticket

### ISSUE THREAD

**Issue by JadsonSL** [marcomoa/Gesior-AAC#7]
Não está realizando a Reply dos Tickets. Estou usando PHP 7.0.2.

Usando a conta GOD para dar a resposta ao ticket, também não grava.

**Comment by marcomoa** [comment]
Altere a tabela para:
CREATE TABLE `tickets_reply` (
  `ticket_replyid` int(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` int(11) NOT NULL,
  `reply_author` varchar(255) DEFAULT NULL,
  `reply_message` text,
  `reply_date` datetime DEFAULT NULL,
  PRIMARY KEY (`ticket_replyid`) USING BTREE,
  KEY `ticket_id_idx` (`ticket_id`) USING BTREE,
  CONSTRAINT `ticket_id` FOREIGN KEY (`ticket_id`) REFERENCES `tickets` (`ticket_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by JadsonSL** [comment]
Corrigido com Pull do banco!
